import re

def escape_markdown(text: str) -> str:
    """
    Escapes special characters in text for safe rendering in Telegram Markdown (V1).
    Characters to escape: _, *, [, `
    """
    if not text:
        return ""
    # Escape backslash first to prevent double-escaping, then the others
    for char in ["\\", "_", "*", "[", "`"]:
        text = text.replace(char, f"\\{char}")
    return text

def clean_telegram_markdown(text: str) -> str:
    r"""
    Cleans standard Markdown generated by Gemini to make it compatible with Telegram Markdown V1.
    Preserves:
      - Bold formatting (converts **bold** to *bold*)
      - Italic formatting (converts *italic* and _italic_ to _italic_)
      - Code blocks (```code```)
      - Inline code (`code`)
    Escapes all raw/unmatched *, _, [, and \ to prevent Telegram parsing exceptions.
    Converts list bullets (* and -) to safe bullet points (•).
    """
    if not text:
        return ""

    # Replace LaTeX arrow formulas with Unicode equivalents
    text = re.sub(r'\$\s*\\(rightarrow|to)\s*\$|\\(rightarrow|to)\b', '→', text)
    text = re.sub(r'\$\s*\\Rightarrow\s*\$|\\Rightarrow\b', '⇒', text)
    text = re.sub(r'\$\s*\\leftarrow\s*\$|\\leftarrow\b', '←', text)
    text = re.sub(r'\$\s*\\Leftarrow\s*\$|\\Leftarrow\b', '⇐', text)
    text = re.sub(r'\$\s*\\leftrightarrow\s*\$|\\leftrightarrow\b', '↔', text)

    # 1. Split by code blocks (```)
    code_block_parts = text.split("```")
    new_parts = []

    for i, part in enumerate(code_block_parts):
        # Odd indices are inside a code block
        if i % 2 == 1:
            # If it is the last element but odd, it is unclosed. Close it safely.
            if i == len(code_block_parts) - 1:
                new_parts.append("```" + part + "```")
            else:
                new_parts.append("```" + part + "```")
        else:
            # Outside code blocks. Split by inline code (`)
            inline_parts = part.split("`")
            new_inline_parts = []
            for j, subpart in enumerate(inline_parts):
                # Odd indices are inside inline code
                if j % 2 == 1:
                    if j == len(inline_parts) - 1:
                        new_inline_parts.append("`" + subpart + "`")
                    else:
                        new_inline_parts.append("`" + subpart + "`")
                else:
                    # Outside inline code. Apply formatting and escaping.
                    new_inline_parts.append(clean_text_block(subpart))
            new_parts.append("".join(new_inline_parts))

    return "".join(new_parts)

def clean_text_block(text: str) -> str:
    """
    Applies formatting conversion and escaping to a block of plain text.
    """
    # 1. Replace bullet points at the start of lines (* or - or + followed by space) with •
    text = re.sub(r'(?m)^(\s*)[*\-+]\s+', r'\1• ', text)

    # 2. Identify and shield valid bold blocks: **bold** -> \x01bold\x01
    text = re.sub(r'\*\*([^\n]+?)\*\*', '\x01\\1\x01', text)

    # 3. Identify and shield valid italic blocks: *italic* -> \x02italic\x02, _italic_ -> \x02italic\x02
    text = re.sub(r'\*([^\n]+?)\*', '\x02\\1\x02', text)
    text = re.sub(r'_([^\n]+?)_', '\x02\\1\x02', text)

    # 4. Escape remaining raw special characters (\, *, _, [)
    escaped = []
    for char in text:
        if char == '\\':
            escaped.append('\\\\')
        elif char in ('*', '_', '['):
            escaped.append('\\' + char)
        else:
            escaped.append(char)
    text = "".join(escaped)

    # 5. Restore shielded bold and italic blocks to Telegram V1 formatting
    text = text.replace('\x01', '*')
    text = text.replace('\x02', '_')

    return text

def split_message(text: str, max_length: int = 4000) -> list:
    """
    Splits a message into multiple parts of at most `max_length` characters,
    splitting on newlines where possible to maintain readable blocks.
    """
    if not text:
        return []
    if len(text) <= max_length:
        return [text]
        
    parts = []
    current_part = ""
    for line in text.split("\n"):
        if len(current_part) + len(line) + 1 > max_length:
            if current_part:
                parts.append(current_part.strip())
                current_part = line + "\n"
            else:
                while len(line) > max_length:
                    parts.append(line[:max_length])
                    line = line[max_length:]
                current_part = line + "\n"
        else:
            current_part += line + "\n"
            
    if current_part:
        parts.append(current_part.strip())
    return parts

